# Generated by Django 3.2.10 on 2021-12-13 16:11

import Vehicle.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle_Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle_Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), Vehicle.models.max_value_current_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_brand', to='Vehicle.vechicle_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_type', to='Vehicle.vechicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Price_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechiclemodel', to='Vehicle.vechicle_model')),
                ('id_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_year', to='Vehicle.vechicle_year')),
            ],
        ),
    ]
