# Generated by Django 3.2.10 on 2021-12-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
