# Generated by Django 3.2.10 on 2021-12-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='vechicle_model',
            name='id_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_type', to='Vehicle.vechicle_type'),
        ),
    ]
