# Generated by Django 3.2.10 on 2021-12-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0004_auto_20211215_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle_model',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_type', to='Vehicle.vechicle_type'),
        ),
    ]
