# Generated by Django 3.2.10 on 2021-12-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0005_alter_vechicle_model_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_list',
            name='id_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vechiclemodel', to='Vehicle.vechicle_model'),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='id_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_year', to='Vehicle.vechicle_year'),
        ),
        migrations.AlterField(
            model_name='vechicle_type',
            name='id_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vechicle_brand', to='Vehicle.vechicle_brand'),
        ),
    ]
